### ISSUE TITLE
issue running under .net core 5.0

### ISSUE THREAD

**Issue by almostEric** [tumtumtum/Shaolinq#110]
This works fine on my local machine, 
                var pgConfiguration = PostgresConfiguration.Create("ReportingServer", _postgresUrl, _postgresUserName, _postgresPassword,commandTimeout: 0);
                PostgresSqlDatabaseContextInfo contextInfo =
                    (PostgresSqlDatabaseContextInfo)pgConfiguration.SqlDatabaseContextInfos[0];
                contextInfo.ConnectionIdleLifetime = 300;
                contextInfo.ConnectionPruningInterval = 10;
                postgresModel = DataAccessModel.BuildDataAccessModel<PostgresModel>(pgConfiguration);

but when pushed to my server I get this error:

Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess, System.String)'.
   at Shaolinq.TypeBuilding.DataAccessModelAssemblyBuilder.BuildAssembly(TypeDescriptorProvider typeDescriptorProvider, DataAccessModelConfiguration configuration)
   at Shaolinq.TypeBuilding.DataAccessModelAssemblyBuilder.GetDataAccessModelAssembly(Type dataAccessModelType, DataAccessModelConfiguration configuration)
   at Shaolinq.TypeBuilding.CachingDataAccessModelAssemblyProvider.GetDataAccessModelAssembly(Type dataAccessModelType, DataAccessModelConfiguration configuration)
   at Shaolinq.DataAccessModel.BuildDataAccessModel(Type dataAccessModelType, DataAccessModelConfiguration configuration)
   at Shaolinq.DataAccessModel.BuildDataAccessModel[T](DataAccessModelConfiguration configuration)

The last line where I call BuildDataAccessModel is where it crashes.

**Comment by tumtumtum** [comment]
Hi @almostEric. What version of .NET is your server running? Is it .NET core? Shaolinq hasn’t been updated to support .NET core yet 😓

**Comment by almostEric** [comment]
yeah, core 5.0. What is weird is it works ok locally. Any timeframe on an update?
